.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. hivemind_qt test_hivemind_qt
clean: FORCE
	$(MAKE) -C .. hivemind_qt_clean test_hivemind_qt_clean
check: FORCE
	$(MAKE) -C .. test_hivemind_qt_check
hivemind-qt hivemind-qt.exe: FORCE
	 $(MAKE) -C .. hivemind_qt
