#!/bin/bash

# This is a thin wrapper around hivemind-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using hivemind-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_HIVEMINDD

# Grab the value of $REAL_HIVEMINDCLI which may be hivemind-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_HIVEMINDCLI}" "$@" | sed 's/\r//'
